@host=http://localhost:5244
@tID=B84D7572-D177-40AD-843D-1CF8EF662B51

POST {{host}}/tournaments/{{tID}}/competitions
Content-Type: application/json

{
    "Competitions": [
        {
            "startDateTime": "{{$datetime iso8601 2 s}}",
            "location": {
                "Country": "USA",
                "State": "California",
                "City": "Los Angeles",
                "Place": "LA Coliseum"
            }
        }
    ]
}