@host=http://localhost:5244
@tID=e3c5e415-313b-432a-8e93-a28fbcf5cdaa

POST {{host}}/tournaments/{{tID}}/competitions
Content-Type: application/json

{
    "Competitions": [
        {
            "startDateTime": "2024-01-01T12:00:00",
            "location": {
                "Country": "USA",
                "State": "California",
                "City": "Los Angeles",
                "Place": "LA Coliseum"
            }
        },
        {
            "startDateTime": "2024-01-02T12:00:00",
            "location": {
                "Country": "USA",
                "State": "California",
                "City": "San Francisco",
                "Place": "AT&T Park"
            }
        }
    ]
}