@host=http://localhost:5244
@tID=4f23de16-883c-492a-a2fe-4f8c304f2258

POST {{host}}/tournaments/{{tID}}/competitions
Content-Type: application/json

{
    "Competitions": [
        {
            "startDateTime": "2024-01-01T12:00:00Z",
            "location": {
                "Country": "USA",
                "State": "California",
                "City": "Los Angeles",
                "Place": "LA Coliseum"
            }
        }
    ]
}