@host=http://localhost:5244
@tID=51c64956-a977-4fef-a949-edd818302d55
@cID=13d6dfef-adea-47cf-990c-4eb1d17ae686

POST {{host}}/tournaments/{{tID}}/competitions/{{cID}}/scores
Content-Type: application/json

{
    "FisherId": "c4133c2a-b020-45fd-aeb4-0ecc37216318",
    "Score": 10
}