//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i8n.Errors.Tournament {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TournamentErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public TournamentErrors() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("i8n.Errors.Tournament.TournamentErrors", typeof(TournamentErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El torneo ya ha terminado..
        /// </summary>
        public static string AlreadyEnded {
            get {
                return ResourceManager.GetString("AlreadyEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La competencia tiene una fecha de inicio anterior..
        /// </summary>
        public static string CompetitionHasEarlierStartDate {
            get {
                return ResourceManager.GetString("CompetitionHasEarlierStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede modificar la inscripción: El pescador ya ha puntuado en este torneo.
        /// </summary>
        public static string FisherHasAlreadyScored {
            get {
                return ResourceManager.GetString("FisherHasAlreadyScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pescador ya está inscrito en el torneo.
        /// </summary>
        public static string InscriptionAlreadyExists {
            get {
                return ResourceManager.GetString("InscriptionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscripción no encontrada.
        /// </summary>
        public static string InscriptionNotFound {
            get {
                return ResourceManager.GetString("InscriptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de inscripción ya existe.
        /// </summary>
        public static string InscriptionNumberAlreadyExists {
            get {
                return ResourceManager.GetString("InscriptionNumberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El torneo ha terminado.
        /// </summary>
        public static string IsOver {
            get {
                return ResourceManager.GetString("IsOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pescador no está inscrito en el torneo.
        /// </summary>
        public static string NotEnrolled {
            get {
                return ResourceManager.GetString("NotEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Torneo no encontrado..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
    }
}
