@host=http://localhost:5244
@tournamentId=4f23de16-883c-492a-a2fe-4f8c304f2258

POST {{host}}/tournaments/{{tournamentId}}/inscriptions
Content-Type: application/json

{
    "fisherId": "b0aedca7-27d0-4583-8ef0-78b476f0d412"
}