@host=http://localhost:5244
@tournamentId=e3c5e415-313b-432a-8e93-a28fbcf5cdaa

POST {{host}}/tournaments/{{tournamentId}}/inscriptions
Content-Type: application/json

{
    "fisherId": "8cf0f7cd-796c-441c-9567-60d79bd08271"
}