@host=http://localhost:5244

POST {{host}}/tournaments
Content-Type: application/json

{
    "name": "New Year Tournament",
    "startDate": "2023-01-01T00:00:00Z",
    "endDate": "2023-02-01T00:00:00Z"
}